### ISSUE TITLE
Print active tabbed interface not working well in v4.0.19+2

### ISSUE THREAD

**Issue by samisd** [wet-boew/wet-boew-styleguide#267] opened 2016-02-02 17:55 UTC
We are having issues with the Tabbed interface we use for the Travel advice and advisories at Travel. It seems to be responding erratically to printing in different browsers. We are currently using v4.0.19+2 and implemented the Print-active class to print only one tab, but it is not indicative to the user what the other tab titles would be or even if there is content there. The Print-active class is supposed to be good for v4.0.15+. but some browsers have printed some content but not all as well. ANy help would be appreciated, thanks.

See figure:
![acores](https://cloud.githubusercontent.com/assets/3083986/12758372/de572c84-c9a9-11e5-9236-f15f130c1cf4.PNG)

**Comment by samisd** [comment] 2016-02-04 20:14
Simitlar issue in the regular issues list

**Comment by RobJohnston** [comment] 2016-11-21 20:40
Duplicate of https://github.com/wet-boew/wet-boew/issues/7373, and it's being dealt with in that issue.

**Closed** 2016-11-22 12:29 UTC
