### ISSUE TITLE
Breadcrumb links are broken in the documentation 

### ISSUE THREAD

**Issue by masterbee** [wet-boew/wet-boew-styleguide#268] opened 2016-02-07 07:30 UTC
Breadcrumb links for "Style Guide" and  "Design Guide" are broken in your documentation.
For example see [Buttons Example Page](http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html)
And check the breadcrumb link

/cc @jaycuse

**Comment by RobJohnston** [comment] 2016-03-17 18:20
Dupe of https://github.com/wet-boew/wet-boew-styleguide/issues/266

**Closed** 2016-03-17 18:40 UTC
