### ISSUE TITLE
Timeline component

### ISSUE THREAD

**Issue by swapnalithakarpspc** [wet-boew/wet-boew-styleguide#396] opened 2020-09-29 12:19 UTC
Hi
I am looking for a timeline component. Something like this.
https://bootsnipp.com/tags/timeline

Can you recommend any particular one? Or does WET already have one?

**Comment by joel-osc** [comment] 2020-09-29 12:22
I am not on the wet-boew team, but I think one is coming soon... here is an example: https://www.canada.ca/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-how-revenue-drop-subsidy-rate-calculated.html#overall. We have already implemented this in DrupalWxt by just grabbing the css from this page and adjusting our markup accordingly.

**Comment by thekodester** [comment] 2020-10-22 23:40
Duplicate of https://github.com/wet-boew/wet-boew/issues/8949

**Closed by thekodester** 2020-10-22 23:40 UTC
Labels: Close: Duplicate
